### ISSUE TITLE
Multiple beneficiaries issue

### ISSUE THREAD

**Issue by mehta0446** [neelpy/cowin#10]
Thank you for developing a wonderful platform for vaccine booking. However, I'm facing issues in booking due to multiple beneficiaries linked to my number. My mother got both the jabs already but it's linked to my account. Hence, when I was trying to book today my 1st dose, the platform sent me an error stating that "reference number xxxxx has already received 2 doses". I went to the COWIN platform to delete my mother's vaccination details but there's no option to do so. Can you please quickly resolve the issue, if possible? I have attached the screenshot of your platform where me and my mother both are shown as the beneficiary.

![Beneficiary error](https://user-images.githubusercontent.com/84233586/118361835-b0c99200-b5aa-11eb-9df4-3bbf74725e3c.PNG)

**Comment by neelpy** [comment]
Will fix this by tomorrow. Meanwhile try with a different account

**Comment by mehta0446** [comment]
Thanks..and yes, already registered a different account. Though, all
today's slots are booked
