### ISSUE TITLE
Shows open slots and the error "This vaccination center is completely booked for the selected date."

### ISSUE THREAD

**Issue by menancer** [neelpy/cowin#26]
When I try to book, it's showing open slots and also the error "This vaccination center is completely booked for the selected date. Please try another date or vaccination center."

And I'm not able to book

Screenshot below.
![image](https://user-images.githubusercontent.com/52341952/119314212-1cd68500-bc92-11eb-8cb7-f650a1e751da.png)

**Comment by vansh-bhatia** [comment]
That's for dose 2, I think we both have the same issue, I raised it, check mine.

**Comment by menancer** [comment]
I was searching by dose 1, though
