### ISSUE TITLE
captcha auto fill

### ISSUE THREAD

**Issue by KanchangC** [neelpy/cowin#29]
Quickly by going through the code, it seems that you have not implemented captcha auto fill, but user has to fill captcha manually. (i am not a javascript pro, i might be wrong). 

captcha autofill is available in my python code. if you want, you can implement the same in your code.

**Comment by KanchangC** [comment]
duplicate of?

**Comment by neelpy** [comment]
#18 

But it doesn't matter because they removed captcha afaik.
