### ISSUE TITLE
Automatically filtering centers with age from registered user

### ISSUE THREAD

**Issue by ainani** [neelpy/cowin#6]
Hi,

If user already selected the person to be vaccinated then let the code provides the results of that age only.
Why we need to provide the results for all age.

Example 1: User want to schedule an appointment for already registered user having age (33 Yrs). Then on results page, it should only give results of centers with 18+ only instead all results.

Thanks

**Comment by neelpy** [comment]
The user is not logged in, so we don't have that data.

**Comment by ainani** [comment]
Hi,
Thanks for prompt response.

But if user is logged in, will have this data and will help user to put very less filter again and again while pressing search button

**Comment by neelpy** [comment]
You are getting something wrong, this is just a tool to get the list of available centers without login, users can't login here. They need to go to the official CoWIN website for that.
